_BASE_: [
  '../datasets/coco_detection.yml',
  '../runtime.yml',
  './_base_/ppyolo_r50vd_dcn.yml',
  './_base_/optimizer_1x.yml',
  './_base_/ppyolo_reader.yml',
]

snapshot_epoch: 16

EvalDataset:
  !COCODataSet
    image_dir: /kaggle/input/coco-2017-dataset/coco2017/test2017
    anno_path: /kaggle/input/coco-2017-dataset/coco2017/annotations/instances_train2017.json
    dataset_dir: /kaggle/input/coco-2017-dataset/coco2017
